# Site settings
title: RickyD
email: datvietburrido@gmail.com
description: "Out of college I was on track to medical school but the MCAT fought me pretty hard and I spent a year as a QA/QC Manager at a Houston beverage bottling company doing all sorts of manual labor and compliance work. It was only in the real world did I realize that the world runs on credit and software. I don't have the credit now but I'm fully capable of learning how to make it by creating software."
baseurl: ""
url: "rickydo.github.io"
twitter_username: statusd0
github_username:  rickyd

# Build settings
markdown: kramdown
permalink: pretty 
