# Site settings
title: RickyD
email: datvietburrido@gmail.com
description: "These are my blog posts while working through phase 0 of DBC."
baseurl: ""
url: "rickydo.github.io"
twitter_username: statusd0
github_username:  rickyd

# Build settings
markdown: kramdown
permalink: pretty 
