# Site settings
title: RickyD
email: datvietburrido@gmail.com
description: "About me"
baseurl: "rickydo.github.io"
url: "rickydo.github.io"
twitter_username: statusd0
github_username:  rickyd

# Build settings
markdown: kramdown
permalink: pretty 
