# Site settings
title: Ricky Do
email: ricky.dop@gmail.com
description: ""
baseurl: ""
url: ""
twitter_username: statusd0
github_username:  rickydo

# Build settings
markdown: kramdown
permalink: pretty 
