# Site settings
title: Ricky Do
email: ricky.dop@gmail.com
description: "These are my blog posts while working through phase 0 of DBC."
baseurl: ""
url: ""
twitter_username: statusd0
github_username:  rickydo

# Build settings
markdown: kramdown
permalink: pretty 
